# for more details see: http://emberjs.com/guides/models/defining-models/

App.Team = DS.Model.extend
  pos: DS.attr 'string'
  gameId: DS.belongsTo 'game' , { inverse: 'teams' }
  gameIds: DS.hasMany 'games', { inverse: 'winnerId' }
  seed: DS.attr 'number'
  school: DS.attr 'string'
  offEff: DS.attr 'string'
  defEff: DS.attr 'string'
  tempo: DS.attr 'string'
  offEfg: DS.attr 'string'
  defEfg: DS.attr 'string'
  offTurnover: DS.attr 'string'
  defTurnover: DS.attr 'string'
  offReb: DS.attr 'string'
  defReb: DS.attr 'string'
  offFtaRate: DS.attr 'string'
  defFtaRate: DS.attr 'string'
  offThreePointPct: DS.attr 'string'
  defThreePointPct: DS.attr 'string'
  offTwoPointPct: DS.attr 'string'
  defTwoPointPct: DS.attr 'string'
  offFtPct: DS.attr 'string'
  defFtPct: DS.attr 'string'
  offBlockPct: DS.attr 'string'
  defBlockPct: DS.attr 'string'
  offStealPct: DS.attr 'string'
  defStealPct: DS.attr 'string'
  off3paPerFga: DS.attr 'string'
  def3paPerFga: DS.attr 'string'
  offAssistRate: DS.attr 'string'
  defAssistRate: DS.attr 'string'
  off3PointDist: DS.attr 'string'
  def3PointDist: DS.attr 'string'
  off2PointDist: DS.attr 'string'
  def2PointDist: DS.attr 'string'
  offFtPointDist: DS.attr 'string'
  defFtPointDist: DS.attr 'string'
  sos: DS.attr 'string'
  benchMinutes: DS.attr 'string'
  experience: DS.attr 'string'
  effectiveHeight: DS.attr 'string'
